### ISSUE TITLE
Make it easy to spin up a dev environment

### ISSUE THREAD

**Issue by 0xmichalis** [DefiLlama/nft-server#12]
A couple of suggestions:
1. add docker-compose with a Postgres container
```yaml
version: '3'
services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ethereum
```
2. automate running migrations in the database maybe with a second container that retries until it successfully applies the migrations in the DB
3. automate filling up event logs in case the table is empty
4. add `config.env.example` with default values matching Postgres username/pass set above
```
DATABASE_URL_INDEXA=postgres://user:password@0.0.0.0:5432/ethereum
DATABASE_URL_NFT=postgres://user:password@0.0.0.0:5432/nft
// ...
```

Then one can quickly start testing adapters with the following commands:
```console
cp config.env.example config.env
docker-compose up -d
node src/adapters/test.js --marketplace=blur
```
